### PR TITLE
Update copyright year

### PR DESCRIPTION
**Pull request by ForNeVeR**

### CODE REVIEW

**Comment by ForNeVeR** [comment]
cc @rexim

**Comment by ForNeVeR** [comment]
You should not care about build fail because this branch simply still has not been properly travisifyed.

**Comment by rexim** [comment]
You lie! You broke the build with your evil copyright updates!!1

**Comment by rexim** [comment]
Anyway, I like where everything is going. So I approve the shit.

**Comment by ForNeVeR** [comment]
Yeah, I lied and now everything will fail! The world will burn in fires! Muhahaha! Ah, I may simply be lying again...

**Pull request merged**
