### PR TITLE
Pet opt-in

### LINKED ISSUE #400: Disable pet per chat
Not everyone wants a pet plugin to be active in their MUC. We should add a configuraion option to disable pet (or to enable it) in the selected chats.

### PR DESCRIPTION
**Pull request by ForNeVeR**
After this change, horta administrator will have to explicitly enable pet for the rooms where he wants to use it.

That's actually a breaking change, but we're still in major version 0, so we're allowed to make such changes without incrementing the major version.

Closes #400.

### CODE REVIEW

**Comment by ForNeVeR** [comment]
I need to investigate failing tests. Regarding to my current experiments, they are failing seemingly at random. Will report back after the investigation.

**Comment by hagane** [comment]
I know that failing test. It's failing because it has a seemingly arbitrary timeout. You can safely ignore it or, if you're serious about it, set it to not run in parallel with other test suites.

**Comment by hagane** [comment]
The test you added -- the one in `PetPluginSpec` looks genuinely broken, though.

**Comment by ForNeVeR** [comment]
Got it. Our static configuration is not the best candidate to be mocked during the unit tests. The problem is it gets configured only once per all the tests, and the resulting configuration is baked into static `Configuration.properties` object first time it's accessed.

I'll create a method to globally deinitialize it for now, but we'll need to invent something more testable in the future (so we could replace or mock that configuration object on a per-plugin basis).

**Comment by ForNeVeR** [comment]
Ah, I've just added these lines to the global config. It was the easiest way.

**Comment by rexim** [comment]
This is pretty good shit! I like it! Approved.

**Comment by ForNeVeR** [comment]
Thank you. Will merge and release the new version soon.

**Pull request closed without merging**
