### PR TITLE
Migrate to container-based infrastructure

### PR DESCRIPTION
**Pull request by ForNeVeR**
Travis [suggests](http://docs.travis-ci.com/user/migrating-from-legacy/) us to do that.

### CODE REVIEW

**Comment by rexim** [comment]
Is it ok that the push has failed?

**Comment by ForNeVeR** [comment]
Well, there are some troubles with PetSpec. I've restarted the build now. We'll file that as a separate issue if it will reproduce.

**Comment by ForNeVeR** [comment]
And it is okay now!

**Comment by rexim** [comment]
Ok, the shit is approved. Thanks!

**Pull request merged**
