### PR TITLE
Bugfix/83

### PR DESCRIPTION
**Pull request by hagane**
A hard fix for #83 
I've took a liberty of performing some clean up (namely, dropped an unused `Lock` from `JabberProtocol` and organized imports in files i touched), so a scrutinous review is in order

### CODE REVIEW

**Comment by hagane** [comment]
You may want to wait for some time, 'cause there is a slight problem with chat management, btw. Horta can and will sometimes lose first private message, if conversation is initiated by user. I'll fix it when I get sane enough to reason about threading.

**Comment by hagane** [comment]
All right, I fixed it. I like the end result even better -- no `ChatOpened` in `MucMessageHandler` and generally terser code

**Comment by ForNeVeR** [comment]
I hope I'll be able to review that tonight, thank you.

**Comment by rexim** [comment]
@ForNeVeR yeah, don't drink too much today ;)

**Comment by rexim** [comment]
@ForNeVeR mixers do not talk, you know!

**Comment by ForNeVeR** [comment]
I have no complaints about this code. Let's test that!

**Pull request merged**
