### PR TITLE
Use total seconds in period comparison

### PR DESCRIPTION
**Pull request by ForNeVeR**
There was a bug in Bash plugin that generated all the "Не так часто, пожалуйста" crap: #344. This commit will fix the bug.

### CODE REVIEW

**Comment by ForNeVeR** [comment]
cc @ttldtor

**Comment by j123123** [comment]
https://en.wikipedia.org/wiki/Year_2038_problem btw :)

**Comment by ForNeVeR** [comment]
So what?

**Comment by j123123** [comment]
Maybe when 32-bit second counter overflow... Nah, just joke. Don't take it seriously

**Comment by ForNeVeR** [comment]
That's a strange joke. We are not using 32-bit integers anywhere to store the timestamp. Joda-time also uses 64-bit `long` everywhere, as even Java does for a couple of years. We haven't this problem in our code.

**Comment by rexim** [comment]
We all gonna die!! \o/

**Comment by ttldtor** [comment]
LGTM. Thank you... WOW! NICE UNITTESTS!!!

**Comment by rexim** [comment]
Mr @ttldtor approved the shit! \o/

**Comment by ForNeVeR** [comment]
Will merge this tonight and release the new version.

**Pull request merged**
