### PR TITLE
Enable integration tests

### LINKED ISSUE #310: Integration tests
We should create a test suite involving a database.

### PR DESCRIPTION
**Pull request by ForNeVeR**
I've refactored code a bit so it can be executed in a test context. Also there is a test example (see `LogPluginSpec`. Now we can easily create integration tests for all new code, it should be sufficient to close #310.

### CODE REVIEW

**Comment by ForNeVeR** [comment]
Mr. @rexim, please review this.

**Comment by rexim** [comment]
I approve this. Please, don't forget to fix #316

**Comment by ForNeVeR** [comment]
I never forget anything (except my first and second name).

**Comment by ForNeVeR** [comment]
Actually I've just noticed that Never **is** my second name! So I think I cannot forget it.

**Pull request merged**
